// web/src/views/system/role/crud.tsx
import { CrudOptions, AddReq, DelReq, EditReq, dict, CrudExpose, compute } from '@fast-crud/fast-crud';
import _ from 'lodash-es';
import * as api from './api';
import { dictionary } from '/@/utils/dictionary';
import { successMessage } from '../../../utils/message';
import {inject} from "vue";
interface CreateCrudOptionsTypes {
	crudOptions: CrudOptions;
}

//此处为crudOptions配置
export const createCrudOptions = function ({ crudExpose, rolePermission }: { crudExpose: CrudExpose; rolePermission: any }): CreateCrudOptionsTypes {
	const pageRequest = async (query: any) => {
		return await api.GetList(query);
	};
	const editRequest = async ({ form, row }: EditReq) => {
		form.id = row.id;
		return await api.UpdateObj(form);
	};
	const delRequest = async ({ row }: DelReq) => {
		return await api.DelObj(row.id);
	};
	const addRequest = async ({ form }: AddReq) => {
		return await api.AddObj(form);
	};

	//权限判定
	const hasPermissions = inject("$hasPermissions")

	// @ts-ignore
	// @ts-ignore
	return {
		crudOptions: {
			request: {
				pageRequest,
				addRequest,
				editRequest,
				delRequest,
			},
			rowHandle: {
				//固定右侧
				fixed: 'right',
				width: 200,
				buttons: {
					view: {
						show: false,
					},
					edit: {
						iconRight: 'Edit',
						type: 'text',
						show:hasPermissions('role:Update')
					},
					remove: {
						iconRight: 'Delete',
						type: 'text',
						show:hasPermissions('role:Delete')
					},
					custom: {
						text: '权限配置',
						type: 'text',
						show:hasPermissions('role:Update'),
						tooltip: {
							placement: 'top',
							content: '权限配置',
						},
						click: (context: any): void => {
							const { row } = context;
							// eslint-disable-next-line no-mixed-spaces-and-tabs
							rolePermission.value.drawer = true;
							rolePermission.value.editedRoleInfo = row;
							rolePermission.value.initGet();
						},
					},
				},
			},
			form: {
				col: { span: 24 },
				labelWidth: '100px',
				wrapper: {
					is: 'el-dialog',
					width: '600px',
				},
			},
			columns: {
				_index: {
					title: '序号',
					form: { show: false },
					column: {
						type: 'index',
						align: 'center',
						width: '70px',
						columnSetDisabled: true, //禁止在列设置中选择
					},
				},
				id: {
					title: 'ID',
					type: 'text',
					column: { show: false },
					search: { show: false },
					form: { show: false },
				},
				name: {
					title: '角色名称',
					type: 'text',
					search: { show: true },
					column: {
						minWidth: 120,
						sortable: 'custom',
					},
					form: {
						rules: [{ required: true, message: '角色名称必填' }],
						component: {
							placeholder: '请输入角色名称',
						},
					},
				},
				key: {
					title: '权限标识',
					type: 'text',
					search: { show: false },
					column: {
						width: 120,
						sortable: 'custom',
					},
					form: {
						rules: [{ required: true, message: '权限标识必填' }],
						placeholder: '输入权限标识',
					},
				},
				sort: {
					title: '排序',
					search: { show: false },
					type: 'number',
					column: {
						width: 90,
						sortable: 'custom',
					},
					form: {
						rules: [{ required: true, message: '排序必填' }],
						value: 1,
					},
				},
				admin: {
					title: '是否管理员',
					search: { show: false },
					type: 'dict-radio',
					dict: dict({
						data: [
							{
								label: '是',
								value: true,
								color: 'success',
							},
							{
								label: '否',
								value: false,
								color: 'danger',
							},
						],
					}),
					column: {
						width: 130,
						sortable: 'custom',
					},
					form: {
						rules: [{ required: true, message: '是否管理员必填' }],
						value: false,
					},
				},
				status: {
					title: '状态',
					search: { show: true },
					type: 'dict-radio',
					column: {
						width:100,
						component: {
							name: 'fs-dict-switch',
							activeText: '',
							inactiveText: '',
							style: '--el-switch-on-color: var(--el-color-primary); --el-switch-off-color: #dcdfe6',
							onChange: compute((context) => {
								return () => {
									api.UpdateObj(context.row).then((res: APIResponseData) => {
										successMessage(res.msg as string);
									});
								};
							}),
						},
					},
					dict: dict({
						data: dictionary('button_status_bool'),
					}),
				},
				update_datetime: {
					title: '更新时间',
					type: 'text',
					search: { show: false },
					column: {
						width: 170,
						sortable: 'custom',
					},
					form: {
						show: false,
						component: {
							placeholder: '输入关键词搜索',
						},
					},
				},
				create_datetime: {
					title: '创建时间',
					type: 'text',
					search: { show: false },
					column: {
						sortable: 'custom',
						width: 170,
					},
					form: {
						show: false,
						component: {
							placeholder: '输入关键词搜索',
						},
					},
				},
				// description: {
				//     title: '备注',
				//     type: 'textarea',
				//     search: {show: false},
				//     form: {
				//         component: {
				//             maxlength: 200,
				//             placeholder: '输入备注',
				//         },
				//     },
				// },
			},
		},
	};
};

// web/src/views/system/menu/components/MenuButtonCom/crud.tsx
import { AddReq, DelReq, EditReq, dict, CreateCrudOptionsRet, CreateCrudOptionsProps } from '@fast-crud/fast-crud';
import * as api from './api';

import { request } from '/@/utils/service';
//此处为crudOptions配置
export const createCrudOptions = function ({ crudExpose, context }: CreateCrudOptionsProps): CreateCrudOptionsRet {
	const pageRequest = async () => {
		if (context!.selectOptions.value.id) {
			return await api.GetList({ menu: context!.selectOptions.value.id } as any);
		} else {
			return undefined;
		}
	};
	const editRequest = async ({ form, row }: EditReq) => {
		return await api.UpdateObj({ ...form, menu: row.menu });
	};
	const delRequest = async ({ row }: DelReq) => {
		return await api.DelObj(row.id);
	};
	const addRequest = async ({ form }: AddReq) => {
		return await api.AddObj({ ...form, ...{ menu: context!.selectOptions.value.id } });
	};
	return {
		crudOptions: {
			search: {
				container: {
					action: {
						//按钮栏配置
						col: {
							span: 8,
						},
					},
				},
			},
			rowHandle: {
				//固定右侧
				fixed: 'right',
				width: 200,
				buttons: {
					view: {
						show: false,
					},
					edit: {
						icon: '',
						type: 'primary',
					},
					remove: {
						icon: '',
						type: 'primary',
					},
				},
			},
			request: {
				pageRequest,
				addRequest,
				editRequest,
				delRequest,
			},
			form: {
				col: { span: 24 },
				labelWidth: '100px',
				wrapper: {
					is: 'el-dialog',
					width: '600px',
				},
			},
			columns: {
				_index: {
					title: '序号',
					form: { show: false },
					column: {
						type: 'index',
						align: 'center',
						width: '70px',
						columnSetDisabled: true, //禁止在列设置中选择
					},
				},
				search: {
					title: '关键词',
					column: { show: false },
					type: 'text',
					search: { show: true },
					form: {
						show: false,
						component: {
							placeholder: '输入关键词搜索',
						},
					},
				},
				id: {
					title: 'ID',
					type: 'text',
					column: { show: false },
					search: { show: false },
					form: { show: false },
				},
				name: {
					title: '权限名称',
					type: 'text',
					search: { show: true },
					column: {
						minWidth: 120,
						sortable: true,
					},
					form: {
						rules: [{ required: true, message: '权限名称必填' }],
						component: {
							placeholder: '输入权限名称搜索',
							props: {
								clearable: true,
								allowCreate: true,
								filterable: true,
							},
						},
						helper: {
							render() {
								return <el-alert title="手动输入" type="warning" description="页面中按钮的名称或者自定义一个名称" />;
							},
						},
					},
				},
				value: {
					title: '权限值',
					type: 'text',
					search: { show: false },
					column: {
						width: 200,
						sortable: true,
					},
					form: {
						rules: [{ required: true, message: '权限标识必填' }],
						placeholder: '输入权限标识',
						helper: {
							render() {
								return <el-alert title="唯一值" type="warning" description="用于判断前端按钮权限或接口权限" />;
							},
						},
					},
				},
				method: {
					title: '请求方式',
					search: { show: false },
					type: 'dict-select',
					column: {
						width: 120,
						sortable: true,
					},
					dict: dict({
						data: [
							{ label: 'GET', value: 0 },
							{ label: 'POST', value: 1, color: 'success' },
							{ label: 'PUT', value: 2, color: 'warning' },
							{ label: 'DELETE', value: 3, color: 'danger' },
						],
					}),
					form: {
						rules: [{ required: true, message: '必填项' }],
					},
				},
				api: {
					title: '接口地址',
					search: { show: false },
					type: 'dict-select',
					dict: dict({
						getData() {
							return request({ url: '/swagger.json' }).then((res: any) => {
								const ret = Object.keys(res.paths);
								const data = [];
								for (const item of ret) {
									const obj: any = {};
									obj.label = item;
									obj.value = item;
									data.push(obj);
								}
								return data;
							});
						},
					}),
					column: {
						minWidth: 250,
						sortable: true,
					},
					form: {
						rules: [{ required: true, message: '必填项' }],
						component: {
							props: {
								allowCreate: true,
								filterable: true,
								clearable: true,
							},
						},
						helper: {
							render() {
								return <el-alert title="请正确填写，以免请求时被拦截。匹配单例使用正则,例如:/api/xx/.*?/" type="warning" />;
							},
						},
					},
				},
			},
		},
	};
};
